### ISSUE TITLE
FAQ needs station landing pad size and distance to star importance note

### ISSUE THREAD

**Issue by SnakeManPMC** [themroc5/eddb.io#25]
http://ross.eddb.io/faq needs information of how critically important is station landing pad size and distance to star. It appears that some/many users ignore these values yet they enter the useless lore data.

You could add http://imgur.com/kYMy1BB link of that ugly landing pad legend in there too.

**Comment by Amunak** [comment]
I agree; we should also make some concensus on roundinng the LY distance. Perhaps not so important, but I've seen several approaches. Taking 124.51 as an example:

- omit the decimals (rounding down), so it becomes 124
- always round up, so that the example becomes 125
- round by first decimal (that's what I do) - example would be 125, but 124.4 would be 124
- some other weird rounding or whatever

I mean it doesn't matter much, but picking one and sticking to it would just trigger my OCD less when I see wrong rounding or something, I don't even know.

Alternatively eddb could just save it as a float in the first place, but that's unnecessary.

**Comment by themroc5** [comment]
doesn't it change anyway? I thought every body in a system moves constantly...
So it doesn't really matter if its up or down rounded...

**Comment by Amunak** [comment]
You are right, it's entirely possible. I guess we'd have to test it. Though when I updated some systems the other day that were like a month or two old they were pretty much on spot, so it's possible they put like average distance there or something.

**Comment by SnakeManPMC** [comment]
When you enter to those remote stations in large systems, like lets say 50,000Ls away, the orbiting cycle or whatever its called can change the distance by HUNDREDS of light seconds.

Well at least I've fixed various user entries in 100's of Ls before. I give the benefit of the doubt for the user who types in the large number that it was actually correct, at the time. However some astronomy geeks might know about this from science point of view, would be glad to hear some facts.

Omitting the decimals is a moot point, EDDB does not support them.

Rounding up, well one Ls doesn't make any difference one way or the other. I just simply put in what the arrival point in system map says, if its 124.51Ls I put in 124, easy.

**Comment by themroc5** [comment]
done!
